### ISSUE TITLE
AttributeError: 'TestCaseFunction' object has no attribute 'execution_count'

### ISSUE THREAD

**Issue by wangzelin007** [pytest-dev/pytest-rerunfailures#206]
Hi pytest admin,
We run all tests using pytest.
But recently we upgraded pytest-rerunfailures to latest (version 11.1) , which caused all tests failed.
This is the error log:
![image](https://user-images.githubusercontent.com/18628534/218044196-50eafb88-7fb7-4ef9-b056-34baa73cd6a5.png)
After I locked pytest-rerunfailures to 11.0 in this [PR](https://github.com/Azure/azure-cli/pull/25419), all tests came back to work.

**Comment by icemac** [comment]
Thank you for your bug report, it seems to be caused by #205 which added the code line where the error happens.

**Comment by rokm** [comment]
This is likely caused by having installed another plugin that overrides `pytest_runtest_protocol` as well; so `pytest` ends up running the other plugin's function, and `execution_count` ends up missing on the item.

 In our case, it seems to be the combination of `pytest-rerunfailures` and `flaky` that is triggering the problem (and although we were playing roulette with which plugin's `pytest_runtest_protocol` gets run, there were apparently compatible enough that the problem went unnoticed).

**Comment by wangzelin007** [comment]
Hi @rokm,
Here's all the softwares we install, but we don't use [flaky](https://pypi.org/project/flaky/):
- MarkupSafe-2.1.2
- Pygments-2.14.0
- alabaster-0.7.13
- argcomplete-2.0.0
- astroid-2.8.6
- attrs-22.2.0
- azdev-0.1.40
- azure-common-1.1.28
- azure-core-1.26.3
- azure-multiapi-storage-1.0.0
- babel-2.11.0
- cachetools-5.3.0
- certifi-2022.12.7
- cffi-1.15.1
- chardet-5.1.0
- charset-normalizer-3.0.1
- colorama-0.4.6
- cryptography-39.0.1
- distlib-0.3.6
- docutils-0.19
- exceptiongroup-1.1.0
- execnet-1.9.0
- filelock-3.9.0
- flake8-4.0.1
- gitdb-4.0.10
- gitpython-3.1.30
- idna-3.4
- imagesize-1.4.1
- iniconfig-2.0.0
- isodate-0.6.1
- isort-5.12.0
- jinja2-3.1.2
- jmespath-1.0.1
- knack-0.10.1
- lazy-object-proxy-1.9.0
- mccabe-0.6.1
- msrest-0.7.1
- oauthlib-3.2.2
- packaging-23.0
- platformdirs-3.0.0
- pluggy-1.0.0
- py-1.11.0
- pycodestyle-2.8.0
- pycparser-2.21
- pyflakes-2.4.0
- pylint-2.11.1
- pyproject-api-1.5.0
- pytest-7.2.1
- pytest-forked-1.4.0
- pytest-html-3.2.0
- pytest-json-report-1.5.0
- pytest-metadata-2.0.4
- pytest-rerunfailures-11.1
- pytest-xdist-3.2.0
- python-dateutil-2.8.2
- pytz-2022.7.1
- pyyaml-6.0
- requests-2.28.2
- requests-oauthlib-1.3.1
- six-1.16.0
- smmap-5.0.0
- snowballstemmer-2.2.0
- sphinx-1.6.7
- sphinxcontrib-serializinghtml-1.1.5
- sphinxcontrib-websupport-1.2.4
- tabulate-0.9.0
- toml-0.10.2
- tomli-2.0.1
- tox-4.4.5
- typing-extensions-4.4.0
- urllib3-1.26.14
- virtualenv-20.19.0
- wheel-0.30.0
- wrapt-1.13.3

**Comment by rokm** [comment]
`pytest-forked` also overrides `pytest_runtest_protocol`.

**Comment by icemac** [comment]
@rokm Do you have an idea how to solve this issue, so that `pytest_runtest_protocol` of multiple plugins is run?

**Comment by rokm** [comment]
> @rokm Do you have an idea how to solve this issue, so that `pytest_runtest_protocol` of multiple plugins is run?

Sorry, I'm not really familiar with `pytest` internals. 

But looking at `pytest_runtest_protocol` implementations, I'd say that plugins that override the protocol are inherently incompatible with each other; because if all plugins' protocols were ran, this would mean that the same item would end up being ran multiple times.  That's why all implementations ([rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures/blob/b20fef5333ce1bf9b327df41cfa9a3f7b282ee5c/pytest_rerunfailures.py#L543-L599), [forked](https://github.com/pytest-dev/pytest-forked/blob/d9d05e257993a3f8329b6e392fa9932de39d6404/src/pytest_forked/__init__.py#L46-L55), and [flaky](https://github.com/box/flaky/blob/1e8c954e7bc818452510d0d4bbcad1d565ddd4d1/flaky/flaky_pytest_plugin.py#L51-L111)) return non-`None`, [which prevents other plugins' implementation from being ran](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.hookspec.pytest_runtest_protocol). 

I suppose you could try raising the priority of this plugin's `pytest_runtest_protocol` via `@hookimpl(runfirst=True)` , but seeing that [forked](https://github.com/pytest-dev/pytest-forked/blob/d9d05e257993a3f8329b6e392fa9932de39d6404/src/pytest_forked/__init__.py#L46) plugin also does that, I have no idea how priority would be resolved...

**Comment by jaimergp** [comment]
Seeing something similar with this config

```
platform win32 -- Python 3.9.16, pytest-7.2.1, pluggy-1.0.0
plugins: cov-4.0.0, mock-3.10.0, rerunfailures-11.1, split-0.8.0, timeout-2.1.0, xdist-3.2.0, xprocess-0.22.2, xdoctest-1.1.1
collecting ... 
```

Error:

```
=================================== ERRORS ====================================
_ ERROR at teardown of ShellWrapperIntegrationTests.test_legacy_activate_deactivate_bash _
Traceback (most recent call last):
  File "C:\conda_bin\envs\conda-test-env\lib\site-packages\pytest_rerunfailures.py", line [518](https://github.com/conda/conda/actions/runs/4176982573/jobs/7233997440#step:8:519), in pytest_runtest_teardown
    item.teardown()
  File "C:\conda_bin\envs\conda-test-env\lib\site-packages\_pytest\unittest.py", line 207, in teardown
    if self._explicit_tearDown is not None:
AttributeError: 'TestCaseFunction' object has no attribute '_explicit_tearDown'
```

[CI logs](https://github.com/conda/conda/actions/runs/4176982573/jobs/7233997440)

Downgrading to pytest-rerunfailures 10.x seems to work.

**Comment by icemac** [comment]
Does https://pypi.org/project/pytest-rerunfailures/11.1.1/ help to fix this issue?

**Comment by wangzelin007** [comment]
> Does https://pypi.org/project/pytest-rerunfailures/11.1.1/ help to fix this issue?

Hi @icemac,
The issue is fixed by 11.1.1

**Comment by wangzelin007** [comment]
> Does https://pypi.org/project/pytest-rerunfailures/11.1.1/ help to fix this issue?

Hi @icemac,
Pytest-rerunfailures-11.1.1 fix the issue, all tests are OK.
